### PR TITLE
Update to CAF 0.17.1 + small fix for Mingw

### PR DESCRIPTION
**Pull request by sourcedelica**

### CODE REVIEW

**Comment by uilianries** [comment]
@sourcedelica Seems like this version is not supported by clang 3.9:

```
error: constexpr constructor never produces a constant expression [-Winvalid-constexpr]

  constexpr node_id() noexcept {

            ^

/home/conan/.conan/data/caf/0.17.1/bincrafters/testing/build/db76947a28dcd653088b70ffa8876965ed6cc5f0/source_subfolder/libcaf_core/caf/node_id.hpp:168:13: note: non-literal type 'intrusive_ptr<caf::node_id::data>' cannot be used in a constant expression
```

https://travis-ci.com/bincrafters/conan-caf/jobs/234370921#L777

**Comment by sourcedelica** [comment]
Same with with Apple Clang 8.3.  Either we can remove those from CI or disable the warning for those two compilers.

**Comment by uilianries** [comment]
@sourcedelica  you can remove them from Travis Matrix, and also add InvalidConfiguration exception.

**Review by uilianries — APPROVED** [review]

**Comment by sourcedelica** [comment]
Thanks!

**Pull request merged**
