### PR TITLE
Merge pull request #4 from bincrafters/eric_0.15.5_work

### PR DESCRIPTION
**Pull request by sourcedelica**
This is to create the first stable branch.   It is effectively the same as the testing/0.15.5 branch.

### CODE REVIEW

**Comment by solvingj** [comment]
Obsoleted now after refresh, closing.  Please audit this recipe to see if there is anything we need to change.

**Comment by sourcedelica** [comment]
The CAF build doesn't support shared libs on Windows, and it doesn't support x86 shared libs.

I'll take a look at the changes you made and revisit the recipe.

**Comment by sourcedelica** [comment]
Are the `CONAN_MODULE_*` environment variables that are used in https://github.com/bincrafters/conan-botan/blob/stable/2.1.0/build.py part of the Bincrafters code or are they unique to that package?  

I've been away for a while and I need to catch up :)

**Comment by solvingj** [comment]
Sorry for the delayed reply, but be sure to work off the `testing/2.1.0` branch

**Comment by sourcedelica** [comment]
Will do.  I didn't get a chance to work on it this weekend due to family obligations.  I am planning on making progress this coming weekend.

**Comment by sourcedelica** [comment]
Fixed in https://github.com/bincrafters/conan-caf/pull/7

**Pull request closed without merging**
